BugBytesHtmx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("films.urls")),
    path("university/", include("university.urls")),
    path("gdp/", include("gdp.urls")),
    path("scores/", include("scores.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from films import views

urlpatterns = [
    path("index/", views.IndexView.as_view(), name="index"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("films/", views.FilmListView.as_view(), name="film-list"),
]

htmx_urlpatterns = [
    path("check-username/", views.check_username, name="check-username"),
    path("add-film/", views.add_film, name="add-film"),
    path("delete-film/<int:pk>/", views.delete_film, name="delete-film"),
    path("search-film", views.search_film, name="search-film"),
    path("clear/", views.clear, name="clear"),
    path("reorder/", views.reorder, name="reorder"),
    path("film-detail/<int:pk>/", views.film_detail, name="film-detail"),
    path("film-list-partial/", views.film_partial, name="film-list-partial"),
    path("upload-photo/<int:pk>/", views.upload_photo, name="upload-photo"),
]

urlpatterns += htmx_urlpatterns

gdp/urls.py
from django.urls import path

from gdp import views

urlpatterns = [
    path("bar/", views.gdp_index, name="gdp_index"),
    path("line/", views.gdp_line, name="gdp_line"),
]

films/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.functions import Lower


class User(AbstractUser):
    pass


class Film(models.Model):
    name = models.CharField(max_length=128, unique=True)
    users = models.ManyToManyField(User, related_name="films", through="UserFilms")  # user.films.all()
    photo = models.ImageField(upload_to="film-photos", null=True, blank=True)

    class Meta:
        ordering = [Lower("name")]

    def __str__(self):
        return self.name


class UserFilms(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ["order"]
        unique_together = ["user", "film"]

    def __str__(self):
        return f"{self.user} - {self.film}"

films/forms.py
from django.contrib.auth.forms import UserCreationForm

from films.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

films/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import FormView, TemplateView
from django.views.generic.list import ListView

from films.forms import RegisterForm
from films.models import Film, UserFilms
from films.utils import get_max_order, reorder_user_films


# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"


class Login(LoginView):
    template_name = "registration/login.html"


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        form.save()  # save the user
        return super().form_valid(form)


class FilmListView(LoginRequiredMixin, ListView):
    template_name = "films.html"
    model = UserFilms
    paginate_by = 20
    context_object_name = "user_films"

    def get_template_names(self):
        if self.request.htmx:
            return "partials/film-list-elements.html"
        return self.template_name

    def get_queryset(self):
        return UserFilms.objects.prefetch_related("film").filter(user=self.request.user).order_by("order")


def check_username(request):
    """Return Response"""
    username = request.POST.get("username")
    if get_user_model().objects.filter(username=username).exists():
        return HttpResponse('<div id="username-error" class="error">Username already exists</div>', status=200)
    return HttpResponse('<div id="username-error" class="success">Username is available</div>', status=200)


@login_required
def add_film(request):
    """Add film to user's list"""
    name = request.POST.get("filmname")

    # get or create the film
    film, is_new = Film.objects.get_or_create(name=name)

    # add the film to the user's list
    if not UserFilms.objects.filter(user=request.user, film=film).exists():
        UserFilms.objects.create(user=request.user, film=film, order=get_max_order(request.user))

    # return success message
    messages.success(request, f"{film.name} added to your list")

    # return paginated template with all user's films
    user_film_qs = UserFilms.objects.filter(user=request.user).order_by("order")
    paginator = Paginator(user_film_qs, 20)
    page_number = request.GET.get("page", 1)
    user_films = paginator.get_page(page_number)
    return render(request, "partials/film-list.html", {"user_films": user_films, "page_obj": user_films})


@login_required
@require_http_methods(["DELETE"])
def delete_film(request, pk):
    """Remove film from user's list"""
    # Delete and reorder user's films
    UserFilms.objects.filter(pk=pk).delete()
    reorder_user_films(request.user)

    # Return paginated list of films
    user_film_qs = UserFilms.objects.filter(user=request.user).order_by("order")
    paginator = Paginator(user_film_qs, 20)
    page_number = request.GET.get("page", 1)
    user_films = paginator.get_page(page_number)
    return render(request, "partials/film-list.html", {"user_films": user_films, "page_obj": user_films})


def search_film(request):
    """Return search results"""
    search_text = request.POST.get("search")

    user_film_ids = UserFilms.objects.filter(user=request.user).values_list("film", flat=True)
    if not search_text:
        results = Film.objects.none()
    else:
        results = Film.objects.filter(name__icontains=search_text).exclude(pk__in=user_film_ids)
    context = {"results": results}
    return render(request, "partials/search-results.html", context)


def clear(request):
    return HttpResponse("<div></div>", status=200)


def reorder(request):
    """Update the order of user's films and return the updated list of films."""
    ordered_user_film_ids = request.POST.getlist("ordered_user_film_ids")
    user_films = []
    updated_user_films = []
    user_film_qs = UserFilms.objects.prefetch_related("film").filter(user=request.user)
    for i, user_film_pk in enumerate(ordered_user_film_ids, start=1):
        user_film = next((u_film for u_film in user_film_qs if u_film.pk == int(user_film_pk)), None)
        if user_film and user_film.order != i:
            user_film.order = i
            updated_user_films.append(user_film)
        user_films.append(user_film)
    UserFilms.objects.bulk_update(updated_user_films, ["order"])
    # Return paginated list of films
    user_film_qs = UserFilms.objects.filter(user=request.user).order_by("order")
    paginator = Paginator(user_film_qs, 20)
    page_number = request.GET.get("page")
    user_films = paginator.get_page(page_number)
    return render(request, "partials/film-list.html", {"user_films": user_films, "page_obj": user_films})


@login_required
def film_detail(request, pk):
    user_film = get_object_or_404(UserFilms, user=request.user, pk=pk)
    context = {"user_film": user_film}
    return render(request, "partials/film-detail.html", context)


@login_required
def film_partial(request):
    user_films = UserFilms.objects.filter(user=request.user).order_by("order")
    return render(request, "partials/film-list.html", {"user_films": user_films})


@login_required
def upload_photo(request, pk):
    user_film = get_object_or_404(UserFilms, user=request.user, pk=pk)
    user_film.film.photo = request.FILES["photo"]
    user_film.film.save()
    return render(request, "partials/film-detail.html", {"user_film": user_film})

films/templates/partials/film-detail.html
<div class="d-flex justify-content-between align-items-top">
    <div>
        <h2 class="text-success mb-4">{{ user_film.film.name }}</h2>
        <p>This film is #{{ user_film.order }} in {{ user_film.user.username|title }}'s list</p>
        <button class="btn btn-primary"
                hx-get="{% url 'film-list-partial' %}"
                hx-target="#film-list"
                hx-push-url="/films"
        >
            Your List
        </button>
    </div>
    
    <div>
        {% if user_film.film.photo %}
            <img src="{{ user_film.film.photo.url }}"
                 alt="{{ user_film.film.name }}"
                 style="max-width: 200px;
                 max-height: 200px;"
            >
        {% else %}
            <p>No photo :/</p>
        {% endif %}
    
        <form hx-encoding="multipart/form-data" hx-post="{% url 'upload-photo' user_film.pk %}" hx-target="#film-list">
            {% csrf_token %}
            <div class="form-group">
                <input type="file" name="photo" class="form-control" id="id_photo">
            </div>
            <button type="submit" class="btn btn-success">Upload Photo</button>
        </form>
    </div>
</div>

films/templates/partials/film-list-elements.html
{% for user_film in user_films %}

<!-- Infinite scroll. If it's the last film, then we need to add a new set of films after it -->
{% if forloop.last %}
  {% if page_obj.has_next %}
  <div
    hx-get="{% url 'film-list' %}?page={{ page_obj.number|add:1 }}"
    hx-trigger="revealed"
    hx-swap="afterend"
    hx-target="this"
  >
  {% endif %}
{% else %}
  <div>
{% endif %}
  <input type="hidden" name="ordered_user_film_ids" value="{{ user_film.pk }}"/>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a
        hx-get="{% url 'film-detail' user_film.pk %}"
        hx-target="#film-list"
        hx-push-url="/film/{{ user_film.film.name }}"
      >
        #{{ user_film.order }} {{ user_film.film.name }}
      </a>
      <span class="badge badge-danger badge-pill" 
        style="cursor: pointer"
        hx-delete="{% url "delete-film" user_film.pk %}"
        hx-target="#film-list"
        hx-confirm="Are you sure you want to delete this film?"
      >X</span>
    </li>
  </div>
{% endfor %}

films/templates/partials/film-list.html
<!-- Header, Film Search and add film button -->
<div class="d-flex justify-content-between align-items-center">
    <p class="lead ml-0">My Films</p>
    <form class="d-flex align-items-center">
        {% csrf_token %}
        <label style="margin-bottom: inherit">
            <input type="text" name="filmname" class="form-control-sm mr-2" placeholder="Enter a film" />
        </label>
        <button hx-post="{% url 'add-film' %}" hx-target="#film-list" type="submit" class="btn btn-success btn-sm">
            Add Film
        </button>
    </form>
</div>

<hr/>

<!-- Section to hold content below the second header -->
<section class="d-flex justify-content-between">

    <!-- Section for displaying all the UserFilms and related pop-ups -->
    <section class="col-6">
    
        <!-- Message pop-ups related to recent actions -->
        {% if messages %}
        <ul class="messages" hx-get="{% url 'clear' %}" hx-trigger="load delay:3s">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    
        <!-- List of UserFilms -->
        {% if user_films %}
            {% csrf_token %}
            <form class="sortable list-group col-xs-12" hx-trigger="end" hx-post="{% url 'reorder' %}" hx-target="#film-list">
                <div class="htmx-indicator">Updating...</div>
                    {% include 'partials/film-list-elements.html' %}
            </form>
        {% else %}
            <p>No films found</p>
        {% endif %}
    </section>

    <!-- Section for displaying search results for Films in the database -->
    <section class="col-6">
        {% include 'partials/search.html'%}
    </section>
</section>

films/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Movie List App</a>

    <div id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'film-list' %}">Films</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'courses' %}">University</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gdp_index' %}">GDP Bar Charts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gdp_line' %}">GDP Line Charts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fixtures' %}">Scores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

films/templates/partials/search-results.html
{% if results %}
  <ul>
    {% for film in results %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ film.name }}
        <span class="badge badge-success badge-pill"
        style="cursor: pointer;"
        hx-post='{% url "add-film" %}'
        hx-vals='{"filmname": "{{ film.name }}"}'
        hx-target="#film-list">add</span>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No results found</p>
{% endif %}

films/templates/partials/search.html
<div class="d-flex justify-content-end mb-4">
  <form>
    {% csrf_token %}
    <label>
      <input
        type="text"
        hx-post="{% url 'search-film' %}"
        hx-target="#results"
        hx-trigger="keyup changed delay:500ms"
        name="search"
        class="form-control-sm mr-2"
        placeholder="Search films..."
        autocomplete="off"
      />
    </label>
  </form>
</div>
<div id="results"></div>